services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5001

  backend:
    build: ./backend
    ports:
      - "5001:5001"
      - "11434:11434"
    environment:
      - FLASK_ENV=production
      - OLLAMA_HOST=http://localhost:11434
      - DOCKER_CONTAINER=true
      - TRANSFORMERS_OFFLINE=1
      - HF_HUB_OFFLINE=1
    volumes:
      - ./backend/data:/app/data:ro
      - ./backend/output:/app/output

volumes:
  whisperx_cache:
